quarkus:
  cache:
    caffeine:
      "greeting":
        expire-after-write: 10s
        initial-capacity: 1
        maximum-size: 1
        metrics-enabled: true
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/data
    password: data
    username: data
  flyway:
    migrate-at-start: true
  scheduler:
    metrics:
      enabled: true

cache:
  greeting:
    refresh-cron: 0/20 * * * * ? *

"%test":
   quarkus:
     datasource:
       db-kind: h2
       jdbc:
         driver: org.h2.Driver
         url: jdbc:h2:tcp://localhost:9092/mem:test